### ISSUE TITLE
examine fighting game design and link videos

### ISSUE THREAD

**Issue by djblooky** [Rigamorphius/AfricanSky#25]
create a combat design document or description

**Comment by djblooky** [comment]
**Game References**

- Scott Pilgrim vs. The World Game
[https://www.youtube.com/watch?v=5FL25DdLqZE](url)

- Castle Crashers
https://www.youtube.com/watch?v=Hi8ms7mV_90

**Comment by Rigamorphius** [comment]
* Top 10 2D Side-Scrolling Games
https://www.youtube.com/watch?v=JjO4Vn8Fd9Q
