### ISSUE TITLE
Player can walk outside of the play area

### ISSUE THREAD

**Issue by djblooky** [Rigamorphius/AfricanSky#86]
Player can walk off of the screen left and right, and on top of the wall/background

- Build: 0.2
- Repro: 100%

**Comment by djblooky** [comment]
Currently in master when you walk up, the camera will follow the player up but go off of the screen

**Comment by andrewfeagley** [comment]
Player has new boxcollider added to their feet to collide with the environment walls. The player should now be able to walk into any object with a rigidbody2d and boxcollider2d on it so long as the object is set to STATIC under the rigidbody2d settings. Just place walls with those components on them on the areas you don't want the player to pass through.
